DROP TABLE IF EXISTS reset CASCADE;

CREATE TABLE reset(
    id SERIAL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE CHECK (email != ''),
    emailcode VARCHAR(300) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
